name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update -qq \
          && sudo apt-get install --no-install-recommends -y \
            libncurses5-dev \
            libreadline-dev
      - name: Build
        run: |
          mkdir -p build \
          && cd build \
          && cmake .. -DALL_STATIC=on \
          && make \
          && tar czfv samba.linux-x86_64.tar.gz samba

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/samba.linux-x86_64.tar.gz
          asset_name: samba.linux-x86_64.tar.gz
          asset_content_type: application/gzip
